# Generated by Django 3.2.7 on 2021-09-21 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suname', models.CharField(max_length=50)),
                ('coid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='college.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.CharField(max_length=50)),
                ('smob', models.CharField(max_length=12)),
                ('sadd', models.CharField(max_length=100)),
                ('scity', models.CharField(max_length=50)),
                ('scourse', models.CharField(max_length=50)),
                ('sbranch', models.CharField(max_length=50)),
                ('sdesc', models.CharField(max_length=500)),
                ('spass', models.CharField(default='12345', max_length=20)),
                ('simg', models.ImageField(default='', upload_to='college/images')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coname', models.CharField(max_length=50)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='college.college')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='suid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display', to='college.course'),
        ),
        migrations.AddField(
            model_name='college',
            name='unid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.university'),
            preserve_default=False,
        ),
    ]
