# Generated by Django 3.2.7 on 2021-09-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20210921_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='cimg',
            field=models.ImageField(default='', upload_to='college/images'),
        ),
    ]
