# Generated by Django 3.2.7 on 2021-10-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_assignment_filemodel_submission_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='submission',
            name='files',
            field=models.ManyToManyField(blank=True, to='college.FileModel'),
        ),
    ]
