# Generated by Django 3.2.7 on 2021-10-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20211007_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='colname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
