# Generated by Django 3.2.7 on 2021-10-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_student_colname'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.course'),
            preserve_default=False,
        ),
    ]
