# Generated by Django 3.2.7 on 2021-10-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_student_coid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='suid',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='coid',
            new_name='branch',
        ),
        migrations.AddField(
            model_name='student',
            name='brid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='college.branch'),
            preserve_default=False,
        ),
    ]
