# Generated by Django 3.2.7 on 2021-10-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_auto_20211013_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='givenFiles',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='files',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='givenfiles',
        ),
        migrations.AddField(
            model_name='teacher',
            name='temail',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='tpass',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
    ]
