# Generated by Django 3.2.7 on 2021-10-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20211017_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='duedate',
        ),
        migrations.AddField(
            model_name='teacher',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
