# Generated by Django 3.2.7 on 2021-10-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_auto_20211018_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='suname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
