# Generated by Django 3.2.7 on 2021-10-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_alter_subject_suname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='suid',
        ),
    ]
