# Generated by Django 3.2.9 on 2022-01-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0015_auto_20220112_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assignment_name',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
