# Generated by Django 3.2.9 on 2022-01-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0016_teacher_assignment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='fees',
            fields=[
                ('fees_id', models.AutoField(primary_key=True, serialize=False)),
                ('sf_name', models.CharField(max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('phone', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
