# Generated by Django 3.2.9 on 2022-01-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0017_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fees',
        ),
    ]
