# Generated by Django 3.2.9 on 2022-01-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0018_delete_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ssubject',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
