# Generated by Django 3.2.9 on 2022-01-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0019_student_ssubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ssem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
